server:
  port: 8080

spring:
  application:
    name: app-server
  datasource:
    url: jdbc:postgresql://localhost:5432/imageprocessing_db
    username: imageuser
    password: imagepass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update          # update para avance 2; cambiar a validate en produccion
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Subida de archivos
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 100MB

# SOAP (Apache CXF)
cxf:
  path: /ws
  servlet.init:
    service-list-path: /services

app:
  jwt:
    secret: "C4mbI4r_P0r_S3cr3t0_S3gur0_d3_256_b1ts_m1n1m0!!"
    expiration-ms: 86400000

  callback-base-url: "http://localhost:8080"
  heartbeat-interval-ms: 30000

  # Directorio donde se guardan las imagenes subidas
  upload-dir: "/tmp/imageprocessing/uploads"

logging:
  level:
    com.imageprocessing: DEBUG
    org.apache.cxf: WARN
    org.springframework.security: WARN
