version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: imageprocessing_db
    environment:
      POSTGRES_DB: imageprocessing_db
      POSTGRES_USER: imageuser
      POSTGRES_PASSWORD: imagepass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/01_schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./database/02_seed.sql:/docker-entrypoint-initdb.d/02_seed.sql

volumes:
  postgres_data:
